---
- hosts: test
# tasks to add a new iptables rule from item_list below & to restart iptables
  tasks:
  - name: Open the one or more IpTables ports
    lineinfile: dest=/etc/sysconfig/iptables
              regexp="^-A INPUT -p {{item.protocol}} -m state --state NEW -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
              line="-A INPUT -p {{item.protocol}} -m state --state NEW -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
              insertbefore="^-A INPUT -j REJECT --reject-with icmp-host-prohibited$"
    with_items:
#   - { protocol: tcp, port: 6556 }
    - { protocol: tcp, port: 80 }
    - { protocol: tcp, port: 443 }
#    - { protocol: tcp, port: 389 }
#    - { protocol: tcp, port: 636 }
#    - { protocol: tcp, port: 88 }
#    - { protocol: tcp, port: 464 }
#    - { protocol: tcp, port: 53 }
#    - { protocol: udp, port: 88 }
#    - { protocol: udp, port: 464 }
#    - { protocol: udp, port: 53 }
#    - { protocol: udp, port: 123 }
  notify:
  - restart iptables

handlers:
  - name: restart iptables
    action: service name=iptables state=restarted
